### PR TITLE
Developers SSO in to AWS

### LINKED ISSUE #56: AWS Configure Not Match Onboarding Instructions
https://shift3.github.io/dj-starter/docs/deploying-your-app/provisioning-infrastructure#quick-start
Onboarding [Google Doc](https://docs.google.com/document/d/1mUnHYB-lIOceWizZorNqr-XJI6cglJUpVa3XgjVt26E/edit) does not match the quickstart of the Dj-Starter
Screenshot from 2023-03-30 15-34-06

It does not include SSO session name, SSO start URL, SSO region, and SSO registration scopes

### PR DESCRIPTION
**Pull request by NicAtak**
## Changes
1. Changed the provisioning infrastructure markdown to include SSO

## Purpose
Documentation between the onboarding assignment and the instructions on this repo are not the same.  

## Approach
This PR addresses the difference between the two by adding in the same instructions from the onboarding assignment. 

## Pre-Testing TODOs
You should have the laptop script installed. 

## Testing Steps
run the commands introduced. 

Closes #56

### CODE REVIEW

**Review by joshwingreene — APPROVED** [review]
This looks good to me. Personally, I'm unable to sign in via the `aws configure sso` command at the moment. (I sent a message to DevOps about this).

So, I won't be able to test this. However, I'll approve this since this is just affecting a markdown file.

Nice work!

**Review by fluturecode — APPROVED** [review]
This looks good.

**Comment by coreyshuman** [comment]
@joshwingreene @fluturecode for future reviews let's make sure that PRs are pointing to the `develop` branch. I prefer to only update `main` when we're cutting a release or pushing a hotfix.

**Comment by fluturecode** [comment]
> @joshwingreene @fluturecode for future reviews let's make sure that PRs are pointing to the `develop` branch. I prefer to only update `main` when we're cutting a release or pushing a hotfix.

Absolutely! Nice catch.

**Pull request merged**
